<?php
/// validation functions

function email_validation($email)
{
   if(preg_match('/^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,3})$/', nvl($email))){
      return true;
	  } else {
      return false;
	  }
}

function empty_validation($value) {
$value=nvl($value); 
	if(empty($value) || $value==""){
		  return false;
	} else {
	return true;
	}

}
function compare_validation($value1,$value2) {
	if(nvl($value1)!=nvl($value2)){
		  return false;
	} else {
	return true;
	}

}


// validation function ends

function nvl(&$var, $default="") {
    return isset($var) ? trim($var) : $default;
} 


function get_referer() {
	$ref = nvl($_SERVER["HTTP_REFERER"]);
        if ($pos = strpos($ref, '?' )) 
             return substr($ref, 0, $pos);
        else
	     return $ref;
}


function odd_even_row($num,$odd_col='#fff',$even_col='#f5f4ea') {
$style='';
if($num%2==0)	{
$style="style='background-color:$odd_col'"	;
} else {
$style="style='background-color:$even_col'"	;	
}

return $style;
} 



function match_referer($allow_ref)  {
  return $allow_ref == get_referer();
 }

function match_refhost($allowed_host)  {
 
list($p,$n,$h,$r) = explode('/',get_referer());
 return $allowed_host == $h; 
 }
   
  

function me() {
    
   if (!empty($_SERVER["REQUEST_URI"])) {
        $s = $_SERVER["REQUEST_URI"];

    } else if (!empty($_SERVER["PHP_SELF"])) {
            $s = $_SERVER["PHP_SELF"];

    } else if (!empty($_SERVER["SCRIPT_NAME"])) {
               $s = $_SERVER["SCRIPT_NAME"];

    } else 
        return false;
if ($pos = strpos($s, '?' )) 
             $s = substr($s, 0, $pos);
         $path_el = explode('/' , $s);
 return $path_el[count($path_el) - 1]; 

}




function mknewpasswd()
{


$the_char = array(
     "a","A","b","B","c","C","d","D","e","E","f","F","g","G","h",
     "H","i","I","j","J", "k","K","l","L","m","M","n","N","o","O",
     "p","P","q","Q","r","R","s","S","t","T", "u","U","v","V","w",
     "W","x","X","y","Y","z","Z","1","2","3","4","5","6","7","8",
     "9","0"
);

$max_elements = count($the_char) - 1;

srand((double)microtime()*1000000);
$rp = '';
for ($i=1; $i<7; $i++) {

$rp .= $the_char[rand(0,$max_elements)];
}
return $rp;


}



function notify_me($to,$error) {
 
$date_time = date('d/m/Y H:i:s');
$headers  = 'MIME-Version: 1.0' . "\r\n";
$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
$headers .= 'From: admin@onlinepccare.com ' . "\r\n" .
    'X-Mailer: PHP/' . phpversion();

$message = "Received at $date_time --".$error;
$mesage = wordwrap($message , 70); 

$subject = "Error generated by mysql operation";
mail($to, $subject , $message , $headers);
       }

function send_mail($to,$from,$subject,$message,$cc='') {
//echo "To:- ".$to."From:-".$from."Subject:- ".$subject."Mesaaage:-".$message;

$date_time = date('d/m/Y H:i:s');
$headers  = 'MIME-Version: 1.0' . "\r\n";
$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
$headers .= "From: $from " . "\r\n" ;
if(!empty($cc)){
$headers .= "Cc: $cc" . "\r\n";
}
$headers .='X-Mailer: PHP/' . phpversion();

$body = wordwrap($message."<p/> ",70); 
return mail($to, $subject , $body , $headers);
      
 }

function checkEmail($email) 
{
   if(eregi("^[a-zA-Z0-9_]+@[a-zA-Z0-9\-]+\.[a-zA-Z0-9\-\.]+$]", $email)) 
   {
      return FALSE;
   }

   list($Username, $Domain) = split("@",$email);
   
  if (dns_get_record($Domain , DNS_MX))
           return TRUE;
  else
if (dns_get_record($Domain, DNS_A))
	return TRUE;
else
       return FALSE;
}

function execute_query($sql,$die=0){

if($die==1){
$rs=mysql_query($sql) or die(mysql_error());
} else {
$rs=mysql_query($sql);
}

return $rs;

}



function record_exists($tablename , $condition) {
 $sql= "select * from $tablename where $condition limit 1";
 $rs = execute_query($sql) or die(mysql_error());
 if (mysql_num_rows($rs) > 0)
  return mysql_fetch_object($rs);
else 
  return false;
 
}



function record_exists_sql($sql) {
  $rs = execute_query($sql,1) ;
 if (mysql_num_rows($rs) > 0)
  return mysql_fetch_object($rs);
else 
  return false;
 
}

function diff_date($date, $days , $mode)
{
list($y,$m,$d)=explode('-', $date);
$secs=86400 * $days;
if ($mode == '+')
$newdate=date("Y-m-d", (mktime(0,0,0,$m,$d,$y) + $secs));
 else
if ($mode == '-')
$newdate=date("Y-m-d", (mktime(0,0,0,$m,$d,$y) - $secs));
else
 return false;
return $newdate;

} 



function yesterday() {

$lday = time() - 24*3600;
return date('Y-m-d', $lday);
}

function get_date( $days , $mode)
{ // count from today
list($y,$m,$d)=explode('-', date("Y-m-d"));
$secs=86400 * $days;
if ($mode == '+')
$newdate=date("Y-m-d", (mktime(0,0,0,$m,$d,$y) + $secs));
 else
if ($mode == '-')
$newdate=date("Y-m-d", (mktime(0,0,0,$m,$d,$y) - $secs));
else
 return false;
return $newdate;

}

function date_conv($old_date,$inc_dec_day)
{
	$exp_date=explode("-",$old_date);
	$year=$exp_date[0];
	$month=$exp_date[1];
	$day=$exp_date[2];
	$day.$inc_dec_day;
	$new_date=date("Y-m-d",mktime(0, 0, 0, $month, $day + $inc_dec_day, $year));
	return $new_date;
	
	// usage : echo date_conv("2011-04-03","-7");
	
}

function validate_phno($phone,$country) {
$pat ='/[\(\)\.\-\\/ ]/';
$replace = ''; 
$pat1='/^0*/';
$pat3='/^\+/';
$phone = preg_replace($pat, $replace,$phone);
$phone = preg_replace($pat3, $replace,$phone);
$phone = preg_replace($pat1, $replace,$phone);

$new = trim($phone);
if (! is_numeric($new) || empty($new))
    return false;
//now check length
$plen = strlen($new);
 
  switch ($country) {
  case "US" : if ($plen > 10 && substr($new,0,1)== '1')
             $new = substr($new,1,$plen-1); 
              break;
  
  case "GB" : if ($plen > 11 && substr($new,0,2)== '44')
             
             $new = substr($new,2,$plen-2); 
              break;

  case "IE" : if ($plen > 10 && substr($new,0,3)== '353')
                  $new = substr($new,3,$plen-3); 
                  break;
      
  case "AU" : if ($plen > 10 && substr($new,0,2)== '61')
 
             $new = substr($new,2,$plen-2); 
             break;
 
   default :   break;
    }
  return $new;
  }





function get_rec_count($tablename,$cond)  {

 $sql = "select count(*) from $tablename where $cond";
  if ($rs=execute_query($sql)) {
        $rec=mysql_fetch_row($rs);
         return $rec[0];
      }
     else return false;
   }

function get_ustz($phone) {
$a=substr($phone,0,3);

if ($rs=record_exists("us_tz",  "AreaCode = '$a'"))
  return $rs->TimeZone;
else
  return '';
  }
  
function insert_record($tablename,$rec,$debug=0) {
$fldnames=$fldvals='';
foreach ($rec as $fld => $val) {
        $val = mysql_real_escape_string($val);
            $fldnames .= $fld.",";
            $fldvals  .= "'$val',"; 
                 }
$fldnames = substr($fldnames,0,-1);
$fldvals = substr($fldvals,0,-1);
$sql = "insert into $tablename ($fldnames) values ($fldvals)"; 
if($debug==1){
echo $sql;
}
if($debug==2){
echo $sql; exit;
}
//echo $sql; die;
$ret=execute_query($sql);
$ins_id=false;
if($ret===true){
$ins_id=mysql_insert_id();	
}

 if (!$ret){
	 if($debug==3){
	 echo mysql_error(); 
	 }
	 if($debug==4){
	 echo mysql_error(); exit;
	 }
    return false;
}
 else {
	 if($debug==5){
	return $ins_id;	 
	 }
	 return true;          
 }

}      


function update_record($tablename,$rec,$keyval,$keyname,$debug=0) {
$fldnames=$fldvals='';
$sql = "update $tablename set ";
foreach ($rec as $fld => $val) {
         $val = mysql_real_escape_string($val);
            $sql.= "$fld ='$val',";
             
                 }
 
 $sql = substr($sql,0,-1);
$sql .= " where $keyname='$keyval'";
 
	if($debug==1){
	echo $sql;
	}
	if($debug==2){
	echo $sql; exit;
	}

 if (!execute_query($sql)){
     if($debug==3){
	 echo mysql_error(); 
	 }
	 if($debug==4){
	 echo mysql_error(); exit;
	 }
    return false; 
}else {
return true;          
}

}    




function delete_record($tbl,$keyval,$keyname)
{
if(isset($keyval) && isset($keyname)){
$sql="DELETE FROM $tbl WHERE $keyname='$keyval'";	
	
 $result=execute_query($sql,1) ;
 if($result)
 return true;
 else
 return false;	
}
else
{
echo "Please pass Delete Condition";
return false;	
}
}

function makeDropdownFromDb($box_name,$tbl,$show_column,$value="",$select_value="",$prop="") {
$sql="select * from $tbl ";
$rs=execute_query($sql);
$count_row=mysql_num_rows($rs);
if(empty($value)){
$value=$show_column;	
}
$html="<select name='$box_name' id='$box_name' $prop>";
$html.="<option value=''> All  </option>";	
	if($count_row > 0){
	    while($option=mysql_fetch_array($rs)){
			$select="";
			if(!empty($select_value)) { 
			     if($select_value==$option[$value])	{
					$select="selected='selected'" ;
				 } else {
					$select="";	 
				 }
			}
			$html.="<option value='$option[$value]' $select>$option[$show_column]</option>";	
		}
	}
$html.="</select>";
return $html;	
}


function drop_box($box_name,$arr,$select_value="",$prop="") {
$html="<select name='$box_name' id='$box_name' $prop>";
//$html.="<option value=''> Select </option>";	
foreach($arr as $key=>$val) 
{
			$select="";
			if(!empty($select_value)) { 
			     if($select_value==$key)	{
					$select="selected='selected'" ;
				 } else {
					$select="";	 
				 }
			}
  $html.="<option value='$key' $select>$val</option>";	
}	
$html.="</select>";
return $html;
}
function drop_box_range($box_name,$min,$max,$select_value="",$prop="") {
$html="<select name='$box_name' id='$box_name' $prop>";
$html.="<option value=''> Select </option>";	
			
			for($i=$min;$i<=$max;$i++) {
			$select="";
			if(!empty($select_value)) { 
			     if($select_value==$key)	{
					$select="selected='selected'" ;
				 } else {
					$select="";	 
				 }
			}
  $html.="<option value='$i' $select>$i</option>";	
  }

$html.="</select>";
return $html;
}

function text_box($box_name,$value="",$prop="") {
$txt="<input type='text' name='$box_name' id='$box_name' value='$value' $prop >";	
return $txt;
}

function hidden_box($box_name,$value="",$prop="") {
$txt="<input type='hidden' name='$box_name' id='$box_name' value='$value' $prop >";	
return $txt;
}

function text_area($box_name,$rows="",$cols="",$value="",$prop="") {
$txt="<textarea name='$box_name' id='$box_name' rows='$rows' cols='$cols' $prop>$value</textarea>";	
return $txt;
}
function password_box($box_name,$value="",$prop="") {
$txt="<input type='password' name='$box_name' id='$box_name' value='$value' $prop >";	
return $txt;
}

function submit_button($box_name,$value,$prop="") {
$txt="<input type='submit' name='$box_name' id='$box_name' value='$value' $prop >";	
return $txt;
}

function button($box_name,$value,$prop="") {
$txt="<input type='button' name='$box_name' id='$box_name' value='$value' $prop >";	
return $txt;
}

function create_day_box($selectname, $selectid, $selval,$extra='') {
	$arr = array('1','2','3','4','5','6','7','8','9');
	$html .= "<select name=\"$selectname\" id=\"$selectid\"style=\"width:auto;\" $extra>";
	for($i=1;$i<=31;$i++) {
		if(in_array($i,$arr)) {
			$i = "0".$i;
		} else {
			$i = $i;
		}
		if($i==$selval){$s = "selected";}
		else {$s = "";}
		$html .= "<option value=\"$i\" $s>$i</option>";
	}
$html .= "</select>";
return $html;
}

function create_mon_box($selectname,$selectid,$selval,$extra='') {
	$mon = array ('01'=>"January" , '02'=>"February", '03'=>"March" , '04'=>"April" , '05'=>"May", '06'=>"June", '07'=>"July", '08'=>"August", '09'=>"September", '10'=>"October", '11'=>"November" , '12'=>"December");
	//$arr = array('1','2','3','4','5','6','7','8','9');
	$html .= "<select name=\"$selectname\" id=\"$selectid\" $extra=''>";
	//echo $this_month = date("m");
	foreach($mon as $key=>$values) {
		if($selval == $key) { $s = "selected";} else {$s = "";}
		$html .= "<option value=\"$key\" $s>$values</option>";
	}
	$html .= "</select>";
	return $html;
}


function create_year_box($selectname,$selectid,$y_min,$y_max,$selval,$extra=''){
	$cur_date = $y_max;
	$html .= "<select name=\"$selectname\" id=\"$selectid\" $extra>";
	for($i=$cur_date;$i>= $y_min;$i--){     
		if ($i==$selval){$s = "selected";}
		else {$s = "";}
	$html .= "<option value=\"$i\" ".$s.">$i</option>" ;
	}                  
	$html .= "</select>";
	return $html;
}
function redirect($url) {
	if(!headers_sent()) {
		header('location: http://'.$_SERVER['HTTP_HOST'].dirname($_SERVER['PHP_SELF']).'/'.$url);
	}
	else{
		die("Could not redirect; Headers already sent (output).");
	}
}

function output_message($message="",$class_name) {
  if (!empty($message)) {
    return "<p class=".$class_name.">{$message}</p>";
  } else {
    return "";
  }
}



function bar_graph($rec) {
$html="<table style='width:100%'>";	
$html.="<tr>";
foreach($rec as $key=>$value) {
$html.="<td style='width:20px;' valign='bottom' align='center'>";
if($value!=0){
$html.="<table height='$value' style='background-color:#800000;'><tr><td style='width:20px;'>&nbsp;</td></tr></table>"; 
}
$html.="</td>";	
$html.="<td style='width:20px;'> &nbsp;   </td>";		
}
	
$html.="</tr>";
$html.="</table>";
return $html;
}

function img_rename($img_name){
$img_ren=str_replace(" ","-",$img_name);
$full_name=time()."_".rand(1000,9999).$img_ren;
return $full_name;
}

function image_upload_validation($file,$dest_path){
$name     = $file['name'];
$type     = $file['type'];
$tmp_name = $file['tmp_name'];
$error    = $file['error'];
$size     = ($file['size'] / 1024) / 1024;



if($error > 0 )
return $error;
if($size > MAX_FILESIZE_UPLOAD)
return 9;
if(empty($name))
return 10;
if(empty($tmp_name))
return 11;
if(false===stristr($type,'image'))
return 12;
if(!is_dir(PARENT_UPLOAD_DIR))
return 15;
if(!is_dir($dest_path)){
  if(imgdir_algo(111)){
   if(!mkdir($dest_path,0777,true))
   return 16;
   else{
     if(!mkdir($dest_path."/thumb",0777,true))
	 return 17;
   }
  } else {
  return 14;
  }
}
	
return 0;	
}
function makeThumb($file,$thumb_dir,$new_name="",$resize="10",$new_width="150",$new_height="150"){
// get file info
$size = getimagesize($file);
$width = $size[0];
$height = $size[1];
if(!$new_name){
$filename = basename($file);
}
else{
$filename = $new_name;
}
// new size
if($resize){
$new_w = ($width*($resize/100));
$new_h = ($height*($resize/100));
}
else{
// tentuin new width and height
$new_w = $new_width;
$new_h = $new_height;

if($width>=$height){
$stat="hor";
}
elseif($width<=$height){
$stat="ver";
}
if($stat=="hor"){
$new_h=$height*$new_w/$width;
}
elseif($stat=="ver"){
$new_w=$width*$new_h/$height;
}
}
// ayo menggambar
$src_img = imagecreatefromjpeg($file);
$dst_img = imagecreatetruecolor($new_w,$new_h);
imagecopyresampled($dst_img, $src_img, 0, 0, 0, 0, $new_w, $new_h, $width, $height);
$chk=imagejpeg($dst_img,$thumb_dir.$filename,100);
// bersihin sampah memori
imagedestroy($src_img);
imagedestroy($dst_img);

return $chk;
}

function upload_image($file,$dest_path){	
return move_uploaded_file($file['tmp_name'],$dest_path);
}


/* edited by naush */



function img_upload($img,$name,$loc,$w,$h){
 //   print "$img.$name.$loc.$w.$h";
    
    define ("MAX_SIZE","5500");
// print "1";
 $errors=0;
 
 
     
        $image =$img["name"];
     //  print $image;
 $uploadedfile = $img['tmp_name'];
 
 // print "2";
  if ($image) 
  { 
   //  print "..3";
  $filename = stripslashes($img['name']);
      // print $filename;
        $extension = getExtension($filename);
        //print $extension;
  $extension = strtolower($extension);
  //print $extension;
 if (($extension != "jpg") && ($extension != "jpeg") 
&& ($extension != "png") && ($extension != "gif")) 
  {
    //   print "4";
echo ' Unknown Image extension ';
$errors=1;
  }
 else
{
     //print "5";
   $size=filesize($img['tmp_name']);
 
if ($size > MAX_SIZE*1024)
{
 echo "You have exceeded the size limit";
 $errors=1;
}
 
if($extension=="jpg" || $extension=="jpeg" )
{
$uploadedfile = $img['tmp_name'];
$src = imagecreatefromjpeg($uploadedfile);
//print "6";
}
else if($extension=="png")
{
    echo "its png........../n";
$uploadedfile = $img['tmp_name'];
$src = imagecreatefrompng($uploadedfile);





}
else 
{
$src = imagecreatefromgif($uploadedfile);
}
 
list($width,$height)=getimagesize($uploadedfile);

//print $width."hhh".$height;
//print "7";


$newwidth=$w;
$newheight=$h;//($height/$width)*$newwidth;
$tmp=imagecreatetruecolor($newwidth,$newheight);








//print "8";
/*$newwidth1=250;
$newheight1=($height/$width)*$newwidth1;
$tmp1=imagecreatetruecolor($newwidth1,$newheight1);
*/
//print "9";
imagecopyresampled($tmp,$src,0,0,0,0,$newwidth,$newheight,
 $width,$height);
/* print "10";
imagecopyresampled($tmp1,$src,0,0,0,0,$newwidth1,$newheight1, 
$width,$height);

print "11";
*/

$img_name = $name."-".$img['name'];
$img_name = str_replace(" ", "-", $img_name);
$img_name = str_replace("/", "-", $img_name);

$filename = $loc.$name;
//$filename1 = "../images/cruise/"."s". $_FILES[$img]['name'];
//print "12";


imagejpeg($tmp,$filename,100);


//imagejpeg($tmp1,$filename1,100);

//print "13";
imagedestroy($src);
imagedestroy($tmp);
//imagedestroy($tmp1);
//print "14";
}
}

//If no errors registred, print the success message

 if(isset($_POST['submit']) && !$errors) 
 { echo "Image Uploaded Successfully!";
return $src;   // mysql_query("update SQL statement ");
  

 }
 

 



 return $src;

}

function getExtension($str) {

         $i = strrpos($str,".");
         if (!$i) { return ""; } 
         $l = strlen($str) - $i;
         $ext = substr($str,$i+1,$l);
         return $ext;
 }































/* edited by naush */
function date_range($first, $last, $format = 'Y-m-d', $step = '+1 day' ) { 

    $dates = array();
    $current = strtotime($first);
    $last = strtotime($last);

    while( $current <= $last ) { 

        $dates[] = date($format, $current);
        $current = strtotime($step, $current);
    }

    return $dates;
}

function prev_month($num_month,$date=''){
    if(!empty($date))
    {
    $cur_month=$date."-01";
    }
    else
    {
        $cur_month=substr($date,0,7)."-01"; 
    }
	$sql="SELECT ('$cur_month' - INTERVAL $num_month MONTH) as dt ";
	$res = mysql_query($sql);
    $result = mysql_fetch_object($res); 
    return $result->dt;
}



function getStartAndEndDate($week, $year)
{

    $time = strtotime("1 January $year", time());
    $day = date('w', $time);
    $time += ((7*$week)+1-$day)*24*3600;
    $return[0] = date('Y-n-j', $time);
    $time += 6*24*3600;
    $return[1] = date('Y-n-j', $time);
    return $return;
}

function br2nl($text) 
{    
   return preg_replace('#<br\s*?/?>#i', "\n", $text);  
}
?> 
